# Generated by Django 4.0.4 on 2022-05-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csw',
            name='title',
            field=models.CharField(choices=[(1, 'Mr'), (2, 'Mrs'), (3, 'Miss'), (4, 'Other')], max_length=200),
        ),
    ]
