# Generated by Django 4.0.4 on 2022-06-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0004_work_contact_csw_house_number_csw_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='education_and_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_your_training', models.CharField(max_length=70, null=True, verbose_name='Title Of Your Training')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('name_of_provider', models.CharField(max_length=70, null=True, verbose_name='Name Of Provider')),
                ('city', models.CharField(max_length=70, null=True, verbose_name='City/Town')),
                ('country', models.CharField(max_length=70, null=True, verbose_name='Country')),
                ('name', models.CharField(max_length=70, null=True, verbose_name='Name')),
                ('job_title', models.CharField(max_length=70, null=True, verbose_name='Job Title')),
                ('telephone_number', models.CharField(max_length=70, null=True, verbose_name='Telephone Number')),
                ('email', models.EmailField(max_length=70, null=True, verbose_name='Email')),
                ('title_of_your_training1', models.CharField(max_length=70, null=True, verbose_name='Title Of Your Training')),
                ('start_date1', models.DateField(max_length=70, null=True, verbose_name='Start Date')),
                ('end_date1', models.DateField(max_length=70, null=True, verbose_name='End Date')),
                ('name_of_pro', models.CharField(max_length=70, null=True, verbose_name='Name Of Provider')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='Address')),
                ('town', models.CharField(max_length=70, null=True, verbose_name='City/Town')),
                ('country1', models.CharField(max_length=70, null=True, verbose_name='Country')),
            ],
        ),
        migrations.AlterField(
            model_name='csw',
            name='mobile_number',
            field=models.CharField(max_length=70, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='work_contact',
            name='mobile_number',
            field=models.CharField(max_length=70, null=True, verbose_name='Mobile Number'),
        ),
    ]
