# Generated by Django 4.0.4 on 2022-06-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0005_education_and_training_alter_csw_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pst_five_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=70, null=True, verbose_name='Organisation')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('post', models.CharField(max_length=70, null=True, verbose_name='Post')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='Address')),
                ('town', models.CharField(max_length=70, null=True, verbose_name='City/Town')),
                ('country1', models.CharField(max_length=70, null=True, verbose_name='Country')),
                ('name_of_manager', models.CharField(max_length=70, null=True, verbose_name='Name Of Manager')),
                ('mobile_number', models.CharField(max_length=70, null=True, verbose_name='Mobile Number')),
                ('email_address', models.EmailField(max_length=70, null=True, verbose_name='Email Address')),
            ],
        ),
    ]
