# Generated by Django 4.0.4 on 2022-06-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0006_pst_five_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='character_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True, verbose_name='Name')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='Address')),
                ('name1', models.CharField(max_length=70, null=True, verbose_name='Name')),
                ('occupation', models.CharField(max_length=70, null=True, verbose_name='Occupation')),
                ('business_address', models.CharField(max_length=70, null=True, verbose_name='Business Address')),
                ('email', models.EmailField(max_length=70, null=True, verbose_name='Email')),
                ('capacity', models.CharField(max_length=70, null=True, verbose_name='Capacity In Which You Know The Applicant')),
            ],
        ),
    ]
