# Generated by Django 4.0.4 on 2022-06-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0007_character_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='practise_outside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_practise', models.CharField(max_length=70, null=True, verbose_name='Name Of Country Practice')),
                ('regulatory_body', models.CharField(max_length=70, null=True, verbose_name='Regulatory Body')),
                ('regulatory_number', models.CharField(max_length=70, null=True, verbose_name='Regulatory Number')),
                ('organisation', models.CharField(max_length=70, null=True, verbose_name='Organisation')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('post', models.CharField(max_length=70, null=True, verbose_name='Post')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=70, null=True, verbose_name='City/Town')),
                ('country', models.CharField(max_length=70, null=True, verbose_name='Country')),
                ('name_of_manager', models.CharField(max_length=70, null=True, verbose_name='Name Of Manager')),
                ('mobile_number', models.CharField(max_length=70, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=70, null=True, verbose_name='Email')),
                ('any_discipinary', models.CharField(choices=[('N', 'NO'), ('Y', 'Yes'), ('I', 'If Yes Give Reason')], max_length=20, null=True, verbose_name='Faced Any Disciplinary Action')),
            ],
        ),
    ]
