# Generated by Django 4.0.4 on 2022-06-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0012_remove_education_and_training_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pst_five_work',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='pst_five_work',
            name='country1',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='pst_five_work',
            name='email_address',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='pst_five_work',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='pst_five_work',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='pst_five_work',
            name='name_of_manager',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Name Of Manager'),
        ),
        migrations.AlterField(
            model_name='pst_five_work',
            name='organisation',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='pst_five_work',
            name='post',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='pst_five_work',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='pst_five_work',
            name='town',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='City/Town'),
        ),
    ]
