# Generated by Django 4.0.4 on 2022-06-06 13:27

from django.db import migrations, models
import django.forms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0013_alter_pst_five_work_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_and_training',
            name='certificates',
            field=models.FileField(null=True, upload_to=django.forms.fields.FilePathField, verbose_name='Certificates'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='any_discipinary',
            field=models.CharField(blank=True, choices=[('N', 'NO'), ('Y', 'Yes'), ('I', 'If Yes Give Reason')], max_length=20, null=True, verbose_name='Faced Any Disciplinary Action'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='country_of_practise',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Name Of Country Practice'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='name_of_manager',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Name Of Manager'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='organisation',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='post',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='regulatory_body',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Regulatory Body'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='regulatory_number',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Regulatory Number'),
        ),
        migrations.AlterField(
            model_name='practise_outside',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
