# Generated by Django 4.0.5 on 2022-06-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0022_customer_delete_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='csw',
            name='passport_pho',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='', verbose_name='Passport Photo'),
        ),
        migrations.AlterField(
            model_name='education_and_training',
            name='certificates',
            field=models.FileField(null=True, upload_to='', verbose_name='Certificates'),
        ),
    ]
